//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class HandSkeletonMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/HandSkeleton";
        public override string RosMessageName => k_RosMessageName;

        public int[] bone_ids;
        public PosRotMsg[] bone_poses;

        public HandSkeletonMsg()
        {
            this.bone_ids = new int[0];
            this.bone_poses = new PosRotMsg[0];
        }

        public HandSkeletonMsg(int[] bone_ids, PosRotMsg[] bone_poses)
        {
            this.bone_ids = bone_ids;
            this.bone_poses = bone_poses;
        }

        public static HandSkeletonMsg Deserialize(MessageDeserializer deserializer) => new HandSkeletonMsg(deserializer);

        private HandSkeletonMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.bone_ids, sizeof(int), deserializer.ReadLength());
            deserializer.Read(out this.bone_poses, PosRotMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.bone_ids);
            serializer.Write(this.bone_ids);
            serializer.WriteLength(this.bone_poses);
            serializer.Write(this.bone_poses);
        }

        public override string ToString()
        {
            return "HandSkeletonMsg: " +
            "\nbone_ids: " + System.String.Join(", ", bone_ids.ToList()) +
            "\nbone_poses: " + System.String.Join(", ", bone_poses.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
